# 端口
server:
  port: 8070

spring:
  # 项目名称
  application:
    name: mall-gateway
  # 注册中心
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.10.50:8848
    # 路由配置
    gateway:
      routes:
        # 商品服务
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        # 开发平台
        - id: app-route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}
